server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0 #操作0号数据库
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 4 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
        max-wait: 1ms #连接池中最大堵塞等待时间
#    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


common:
  path: E:\img\
